service:
  name: gcp-ml-image-labeling-service

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: nodejs10
  region: europe-west1 # OPTIONAL: Edit if you want to
  project: {PROJECT_ID} # EDIT THIS to your value
  credentials: ~/.gcloud/{KEYFILE}.json # EDIT THIS to your value
  memorySize: 1024
  timeout: 10s

functions:
  getLabels:
    handler: getLabels
    events:
      - http: getLabels
        method: GET